// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_receipts_create_receiptSchema = {
    properties: {
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['retailer_id', 'file'],
    title: 'Body_receipts-create_receipt'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NestedPriceObservationSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date',
            description: 'Date of the price list or observation.'
        },
        retailer_product_code: {
            type: 'string',
            maxLength: 32,
            title: 'Retailer Product Code',
            description: 'Retailer scoped product code. Original CSV column: šifra or ŠIFRA PROIZVODA.'
        },
        source_product_name: {
            type: 'string',
            maxLength: 255,
            title: 'Source Product Name',
            description: 'Product name exactly as it appeared in the source price list.'
        },
        price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Eur',
            description: 'Current product price from the source price list.'
        },
        unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Eur',
            description: 'Original CSV column: cijena za jedinicu mjere (EUR) or CIJENA ZA JEDINICU MJERE.'
        },
        is_special_sale: {
            type: 'boolean',
            title: 'Is Special Sale',
            description: 'Whether price_eur comes from the special sale price column.',
            default: false
        },
        source_file_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File Name',
            description: 'Name of the imported source CSV file.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        store: {
            '$ref': '#/components/schemas/StorePublic'
        }
    },
    type: 'object',
    required: ['product_id', 'retailer_id', 'store_id', 'observed_date', 'retailer_product_code', 'source_product_name', 'unit_price_eur', 'id', 'retailer', 'store'],
    title: 'NestedPriceObservation'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PriceMoverSchema = {
    properties: {
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        },
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        current_date: {
            type: 'string',
            format: 'date',
            title: 'Current Date'
        },
        previous_date: {
            type: 'string',
            format: 'date',
            title: 'Previous Date'
        },
        previous_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Previous Price Eur'
        },
        current_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Current Price Eur'
        },
        absolute_change_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Absolute Change Eur'
        },
        percent_change: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Percent Change'
        }
    },
    type: 'object',
    required: ['product', 'retailer', 'current_date', 'previous_date', 'previous_price_eur', 'current_price_eur', 'absolute_change_eur', 'percent_change'],
    title: 'PriceMover'
} as const;

export const PriceMoversPublicSchema = {
    properties: {
        current_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Date'
        },
        previous_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Previous Date'
        },
        price_drops: {
            items: {
                '$ref': '#/components/schemas/PriceMover'
            },
            type: 'array',
            title: 'Price Drops'
        },
        price_increases: {
            items: {
                '$ref': '#/components/schemas/PriceMover'
            },
            type: 'array',
            title: 'Price Increases'
        }
    },
    type: 'object',
    required: ['current_date', 'previous_date', 'price_drops', 'price_increases'],
    title: 'PriceMoversPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductListBaseSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'User-facing product list name, for example Weekly groceries.'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Optional notes about what this product list is for.'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ProductListBase'
} as const;

export const ProductListItemAlternativeCreateSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        }
    },
    type: 'object',
    required: ['product_id'],
    title: 'ProductListItemAlternativeCreate'
} as const;

export const ProductListItemAlternativeDetailPublicSchema = {
    properties: {
        product_list_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product List Item Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        }
    },
    type: 'object',
    required: ['product_list_item_id', 'product_id', 'id', 'product'],
    title: 'ProductListItemAlternativeDetailPublic'
} as const;

export const ProductListItemAlternativesBulkCreateSchema = {
    properties: {
        product_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Product Ids'
        }
    },
    type: 'object',
    required: ['product_ids'],
    title: 'ProductListItemAlternativesBulkCreate'
} as const;

export const ProductListItemAlternativesBulkCreateResultSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductListItemAlternativeDetailPublic'
            },
            type: 'array',
            title: 'Data'
        },
        created_count: {
            type: 'integer',
            title: 'Created Count'
        },
        skipped_count: {
            type: 'integer',
            title: 'Skipped Count'
        }
    },
    type: 'object',
    required: ['data', 'created_count', 'skipped_count'],
    title: 'ProductListItemAlternativesBulkCreateResult'
} as const;

export const ProductListItemCreateSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Quantity',
            default: '1'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    required: ['product_id'],
    title: 'ProductListItemCreate'
} as const;

export const ProductListItemDetailPublicSchema = {
    properties: {
        product_list_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product List Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity',
            description: 'How many units of the canonical product are planned for this list.',
            default: '1'
        },
        note: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note',
            description: 'Optional note for this list item.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        },
        alternatives: {
            items: {
                '$ref': '#/components/schemas/ProductListItemAlternativeDetailPublic'
            },
            type: 'array',
            title: 'Alternatives'
        }
    },
    type: 'object',
    required: ['product_list_id', 'product_id', 'id', 'product'],
    title: 'ProductListItemDetailPublic'
} as const;

export const ProductListItemUpdateSchema = {
    properties: {
        quantity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        }
    },
    type: 'object',
    title: 'ProductListItemUpdate'
} as const;

export const ProductListPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'User-facing product list name, for example Weekly groceries.'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: 'Optional notes about what this product list is for.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ProductListPublic'
} as const;

export const ProductListRetailerPriceHistoryPointSchema = {
    properties: {
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date'
        },
        total_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Price Eur'
        },
        matched_item_count: {
            type: 'integer',
            title: 'Matched Item Count'
        },
        total_item_count: {
            type: 'integer',
            title: 'Total Item Count'
        },
        has_missing_prices: {
            type: 'boolean',
            title: 'Has Missing Prices'
        },
        has_special_sale: {
            type: 'boolean',
            title: 'Has Special Sale'
        }
    },
    type: 'object',
    required: ['retailer', 'observed_date', 'total_price_eur', 'matched_item_count', 'total_item_count', 'has_missing_prices', 'has_special_sale'],
    title: 'ProductListRetailerPriceHistoryPoint'
} as const;

export const ProductListUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProductListUpdate'
} as const;

export const ProductListsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductListPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductListsPublic'
} as const;

export const ProductPublicSchema = {
    properties: {
        barcode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Barcode',
            description: 'Cross retailer product identifier when present. Original CSV column: barkod or BARKOD.'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'Canonical or first seen product name. Original CSV column: naziv or NAZIV PROIZVODA.'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand',
            description: 'Original CSV column: marka or MARKA PROIZVODA.'
        },
        net_quantity: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Quantity',
            description: 'Raw net quantity from the CSV. Original CSV column: neto količina or NETO KOLIČINA.'
        },
        unit_of_measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Of Measure',
            description: 'Original CSV column: jedinica mjere or JEDINICA MJERE.'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category',
            description: 'Original CSV column: kategorija proizvoda or KATEGORIJA PROIZVODA.'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url',
            description: 'Product image URL fetched from Open Food Facts.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        latest_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Price Eur',
            description: 'Product price from one latest available observation.'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const ReceiptItemReviewPublicSchema = {
    properties: {
        receipt_id: {
            type: 'string',
            format: 'uuid',
            title: 'Receipt Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        price_observation_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Observation Id'
        },
        line_number: {
            type: 'integer',
            title: 'Line Number'
        },
        raw_name: {
            type: 'string',
            maxLength: 255,
            title: 'Raw Name',
            description: 'Product name exactly as parsed from the receipt.'
        },
        normalized_raw_name: {
            type: 'string',
            maxLength: 255,
            title: 'Normalized Raw Name',
            description: 'Normalized search form of raw_name.'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity',
            description: 'Purchased quantity parsed from the receipt line.'
        },
        unit_of_measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Of Measure',
            description: 'Unit parsed from the receipt line when present, for example kg.'
        },
        unit_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price Eur',
            description: 'Unit price in EUR parsed from the receipt line.'
        },
        line_total_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Line Total Eur',
            description: 'Final line total in EUR after any receipt-level line adjustments.'
        },
        is_skipped: {
            type: 'boolean',
            title: 'Is Skipped',
            description: 'Whether the user intentionally ignored this receipt line.',
            default: false
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProductPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['receipt_id', 'line_number', 'raw_name', 'normalized_raw_name', 'quantity', 'line_total_eur', 'id'],
    title: 'ReceiptItemReviewPublic'
} as const;

export const ReceiptItemUpdateSchema = {
    properties: {
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        is_skipped: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Skipped'
        }
    },
    type: 'object',
    title: 'ReceiptItemUpdate'
} as const;

export const ReceiptPublicSchema = {
    properties: {
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Store Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        purchase_datetime: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Purchase Datetime',
            description: 'Datetime when the purchase was made, as parsed from the receipt.'
        },
        total_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Eur',
            description: 'Final receipt total in EUR.'
        },
        file_key: {
            type: 'string',
            maxLength: 512,
            title: 'File Key',
            description: 'Storage key or path for the uploaded receipt file.'
        },
        status: {
            '$ref': '#/components/schemas/ReceiptStatus',
            description: 'User review lifecycle status for the receipt.',
            default: 'draft'
        },
        raw_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Text',
            description: 'Text extracted from the uploaded receipt file.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['retailer_id', 'file_key', 'id'],
    title: 'ReceiptPublic'
} as const;

export const ReceiptStatusSchema = {
    type: 'string',
    enum: ['draft', 'completed'],
    title: 'ReceiptStatus'
} as const;

export const ReceiptUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ReceiptStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ReceiptUpdate'
} as const;

export const ReceiptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReceiptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReceiptsPublic'
} as const;

export const RetailerDailyRetailPriceHistoryPointSchema = {
    properties: {
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date'
        },
        average_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Price Eur'
        },
        min_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Price Eur'
        },
        max_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Price Eur'
        },
        has_special_sale: {
            type: 'boolean',
            title: 'Has Special Sale'
        }
    },
    type: 'object',
    required: ['retailer', 'observed_date', 'average_price_eur', 'min_price_eur', 'max_price_eur', 'has_special_sale'],
    title: 'RetailerDailyRetailPriceHistoryPoint'
} as const;

export const RetailerPriceObservationSummarySchema = {
    properties: {
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date'
        },
        average_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Price Eur'
        },
        min_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Price Eur'
        },
        max_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Price Eur'
        },
        average_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average Unit Price Eur'
        },
        min_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Min Unit Price Eur'
        },
        max_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Max Unit Price Eur'
        },
        store_count: {
            type: 'integer',
            title: 'Store Count'
        },
        observation_count: {
            type: 'integer',
            title: 'Observation Count'
        },
        has_store_price_variance: {
            type: 'boolean',
            title: 'Has Store Price Variance'
        },
        has_special_sale: {
            type: 'boolean',
            title: 'Has Special Sale'
        }
    },
    type: 'object',
    required: ['retailer', 'observed_date', 'average_price_eur', 'min_price_eur', 'max_price_eur', 'average_unit_price_eur', 'min_unit_price_eur', 'max_unit_price_eur', 'store_count', 'observation_count', 'has_store_price_variance', 'has_special_sale'],
    title: 'RetailerPriceObservationSummary'
} as const;

export const RetailerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name',
            description: 'Retailer name, for example Konzum or Interspar.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RetailerPublic'
} as const;

export const SimilarProductPublicSchema = {
    properties: {
        product: {
            '$ref': '#/components/schemas/ProductPublic'
        },
        retailers: {
            items: {
                '$ref': '#/components/schemas/RetailerPublic'
            },
            type: 'array',
            title: 'Retailers'
        },
        latest_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Price Eur'
        },
        average_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Price Eur'
        },
        latest_observed_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Observed Date'
        },
        score: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Score'
        }
    },
    type: 'object',
    required: ['product', 'retailers', 'latest_price_eur', 'average_price_eur', 'latest_observed_date', 'score'],
    title: 'SimilarProductPublic'
} as const;

export const StorePublicSchema = {
    properties: {
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_code: {
            type: 'string',
            maxLength: 64,
            title: 'Store Code',
            description: 'Retailer scoped store code from the source file or retailer data.'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'Store name, for example a branch or supermarket name.'
        },
        address: {
            type: 'string',
            maxLength: 255,
            title: 'Address',
            description: 'Store address when available.',
            default: ''
        },
        prefix: {
            type: 'string',
            maxLength: 255,
            title: 'Prefix',
            description: 'Prefix to be used in finding corresponding file in list of stores',
            default: ''
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['retailer_id', 'store_code', 'name', 'id'],
    title: 'StorePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;