// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NestedPriceObservationSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date',
            description: 'Date of the price list or observation.'
        },
        retailer_product_code: {
            type: 'string',
            maxLength: 32,
            title: 'Retailer Product Code',
            description: 'Retailer scoped product code. Original CSV column: šifra or ŠIFRA PROIZVODA.'
        },
        source_product_name: {
            type: 'string',
            maxLength: 255,
            title: 'Source Product Name',
            description: 'Product name exactly as it appeared in the source price list.'
        },
        price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Eur',
            description: 'Current product price from the source price list.'
        },
        unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price Eur',
            description: 'Original CSV column: cijena za jedinicu mjere (EUR) or CIJENA ZA JEDINICU MJERE.'
        },
        is_special_sale: {
            type: 'boolean',
            title: 'Is Special Sale',
            description: 'Whether price_eur comes from the special sale price column.',
            default: false
        },
        source_file_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source File Name',
            description: 'Name of the imported source CSV file.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        store: {
            '$ref': '#/components/schemas/StorePublic'
        }
    },
    type: 'object',
    required: ['product_id', 'retailer_id', 'store_id', 'observed_date', 'retailer_product_code', 'source_product_name', 'unit_price_eur', 'id', 'retailer', 'store'],
    title: 'NestedPriceObservation'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        barcode: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Barcode',
            description: 'Cross retailer product identifier when present. Original CSV column: barkod or BARKOD.'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'Canonical or first seen product name. Original CSV column: naziv or NAZIV PROIZVODA.'
        },
        alternative_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alternative Name',
            description: 'Alternative product name fetched from Open Food Facts, preferring Croatian names.'
        },
        brand: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand',
            description: 'Original CSV column: marka or MARKA PROIZVODA.'
        },
        net_quantity: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Quantity',
            description: 'Raw net quantity from the CSV. Original CSV column: neto količina or NETO KOLIČINA.'
        },
        unit_of_measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 16
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Of Measure',
            description: 'Original CSV column: jedinica mjere or JEDINICA MJERE.'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category',
            description: 'Original CSV column: kategorija proizvoda or KATEGORIJA PROIZVODA.'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url',
            description: 'Product image URL fetched from Open Food Facts.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ProductPublic'
} as const;

export const ProductsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProductsPublic'
} as const;

export const RetailerDailyRetailPriceHistoryPointSchema = {
    properties: {
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date'
        },
        average_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Price Eur'
        },
        min_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Price Eur'
        },
        max_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Price Eur'
        },
        has_special_sale: {
            type: 'boolean',
            title: 'Has Special Sale'
        }
    },
    type: 'object',
    required: ['retailer', 'observed_date', 'average_price_eur', 'min_price_eur', 'max_price_eur', 'has_special_sale'],
    title: 'RetailerDailyRetailPriceHistoryPoint'
} as const;

export const RetailerPriceObservationSummarySchema = {
    properties: {
        retailer: {
            '$ref': '#/components/schemas/RetailerPublic'
        },
        observed_date: {
            type: 'string',
            format: 'date',
            title: 'Observed Date'
        },
        average_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Average Price Eur'
        },
        min_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Min Price Eur'
        },
        max_price_eur: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Price Eur'
        },
        average_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Average Unit Price Eur'
        },
        min_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Min Unit Price Eur'
        },
        max_unit_price_eur: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Max Unit Price Eur'
        },
        store_count: {
            type: 'integer',
            title: 'Store Count'
        },
        observation_count: {
            type: 'integer',
            title: 'Observation Count'
        },
        has_store_price_variance: {
            type: 'boolean',
            title: 'Has Store Price Variance'
        },
        has_special_sale: {
            type: 'boolean',
            title: 'Has Special Sale'
        }
    },
    type: 'object',
    required: ['retailer', 'observed_date', 'average_price_eur', 'min_price_eur', 'max_price_eur', 'average_unit_price_eur', 'min_unit_price_eur', 'max_unit_price_eur', 'store_count', 'observation_count', 'has_store_price_variance', 'has_special_sale'],
    title: 'RetailerPriceObservationSummary'
} as const;

export const RetailerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 64,
            title: 'Name',
            description: 'Retailer name, for example Konzum or Interspar.'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'RetailerPublic'
} as const;

export const StorePublicSchema = {
    properties: {
        retailer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Retailer Id'
        },
        store_code: {
            type: 'string',
            maxLength: 64,
            title: 'Store Code',
            description: 'Retailer scoped store code from the source file or retailer data.'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name',
            description: 'Store name, for example a branch or supermarket name.'
        },
        address: {
            type: 'string',
            maxLength: 255,
            title: 'Address',
            description: 'Store address when available.',
            default: ''
        },
        prefix: {
            type: 'string',
            maxLength: 255,
            title: 'Prefix',
            description: 'Prefix to be used in finding corresponding file in list of stores',
            default: ''
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['retailer_id', 'store_code', 'name', 'id'],
    title: 'StorePublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;