// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { DashboardReadPriceMoversData, DashboardReadPriceMoversResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, ProductsReadProductsData, ProductsReadProductsResponse, ProductsReadProductData, ProductsReadProductResponse, ProductsProductPriceObservationsData, ProductsProductPriceObservationsResponse, ProductsProductDailyRetailPriceHistoryChartData, ProductsProductDailyRetailPriceHistoryChartResponse, ProductsGroupedProductPriceObservationsData, ProductsGroupedProductPriceObservationsResponse, ReceiptsCreateReceiptData, ReceiptsCreateReceiptResponse, ReceiptsReadReceiptsData, ReceiptsReadReceiptsResponse, ReceiptsReadReceiptData, ReceiptsReadReceiptResponse, ReceiptsUpdateReceiptData, ReceiptsUpdateReceiptResponse, ReceiptsDeleteReceiptData, ReceiptsDeleteReceiptResponse, ReceiptsReadReceiptItemsData, ReceiptsReadReceiptItemsResponse, ReceiptsUpdateReceiptItemData, ReceiptsUpdateReceiptItemResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class DashboardService {
    /**
     * Read Price Movers
     * @param data The data for the request.
     * @param data.limit
     * @returns PriceMoversPublic Successful Response
     * @throws ApiError
     */
    public static readPriceMovers(data: DashboardReadPriceMoversData = {}): CancelablePromise<DashboardReadPriceMoversResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/dashboard/price-movers',
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ProductsService {
    /**
     * Read Products
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.q
     * @returns ProductsPublic Successful Response
     * @throws ApiError
     */
    public static readProducts(data: ProductsReadProductsData = {}): CancelablePromise<ProductsReadProductsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products',
            query: {
                skip: data.skip,
                limit: data.limit,
                q: data.q
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Product
     * @param data The data for the request.
     * @param data.productId
     * @returns ProductPublic Successful Response
     * @throws ApiError
     */
    public static readProduct(data: ProductsReadProductData): CancelablePromise<ProductsReadProductResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/{product_id}',
            path: {
                product_id: data.productId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Product Price Observations
     * @param data The data for the request.
     * @param data.productId
     * @returns NestedPriceObservation Successful Response
     * @throws ApiError
     */
    public static productPriceObservations(data: ProductsProductPriceObservationsData): CancelablePromise<ProductsProductPriceObservationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/{product_id}/price-observations',
            path: {
                product_id: data.productId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Product Daily Retail Price History Chart
     * @param data The data for the request.
     * @param data.productId
     * @returns RetailerDailyRetailPriceHistoryPoint Successful Response
     * @throws ApiError
     */
    public static productDailyRetailPriceHistoryChart(data: ProductsProductDailyRetailPriceHistoryChartData): CancelablePromise<ProductsProductDailyRetailPriceHistoryChartResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/{product_id}/price-history/retail/chart',
            path: {
                product_id: data.productId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Grouped Product Price Observations
     * @param data The data for the request.
     * @param data.productId
     * @returns RetailerPriceObservationSummary Successful Response
     * @throws ApiError
     */
    public static groupedProductPriceObservations(data: ProductsGroupedProductPriceObservationsData): CancelablePromise<ProductsGroupedProductPriceObservationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/products/{product_id}/price-observations/grouped',
            path: {
                product_id: data.productId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ReceiptsService {
    /**
     * Create Receipt
     * @param data The data for the request.
     * @param data.formData
     * @returns Receipt Successful Response
     * @throws ApiError
     */
    public static createReceipt(data: ReceiptsCreateReceiptData): CancelablePromise<ReceiptsCreateReceiptResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/receipts',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Receipts
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ReceiptsPublic Successful Response
     * @throws ApiError
     */
    public static readReceipts(data: ReceiptsReadReceiptsData = {}): CancelablePromise<ReceiptsReadReceiptsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/receipts',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Receipt
     * @param data The data for the request.
     * @param data.receiptId
     * @returns Receipt Successful Response
     * @throws ApiError
     */
    public static readReceipt(data: ReceiptsReadReceiptData): CancelablePromise<ReceiptsReadReceiptResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/receipts/{receipt_id}',
            path: {
                receipt_id: data.receiptId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Receipt
     * @param data The data for the request.
     * @param data.receiptId
     * @param data.requestBody
     * @returns Receipt Successful Response
     * @throws ApiError
     */
    public static updateReceipt(data: ReceiptsUpdateReceiptData): CancelablePromise<ReceiptsUpdateReceiptResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/receipts/{receipt_id}',
            path: {
                receipt_id: data.receiptId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Receipt
     * @param data The data for the request.
     * @param data.receiptId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteReceipt(data: ReceiptsDeleteReceiptData): CancelablePromise<ReceiptsDeleteReceiptResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/receipts/{receipt_id}',
            path: {
                receipt_id: data.receiptId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Receipt Items
     * @param data The data for the request.
     * @param data.receiptId
     * @returns ReceiptItemReviewPublic Successful Response
     * @throws ApiError
     */
    public static readReceiptItems(data: ReceiptsReadReceiptItemsData): CancelablePromise<ReceiptsReadReceiptItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/receipts/{receipt_id}/items',
            path: {
                receipt_id: data.receiptId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Receipt Item
     * @param data The data for the request.
     * @param data.receiptId
     * @param data.itemId
     * @param data.requestBody
     * @returns ReceiptItemReviewPublic Successful Response
     * @throws ApiError
     */
    public static updateReceiptItem(data: ReceiptsUpdateReceiptItemData): CancelablePromise<ReceiptsUpdateReceiptItemResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/receipts/{receipt_id}/items/{item_id}',
            path: {
                receipt_id: data.receiptId,
                item_id: data.itemId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check'
        });
    }
}