// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NestedPriceObservation = {
    product_id: string;
    retailer_id: string;
    store_id: string;
    /**
     * Date of the price list or observation.
     */
    observed_date: string;
    /**
     * Retailer scoped product code. Original CSV column: šifra or ŠIFRA PROIZVODA.
     */
    retailer_product_code: string;
    /**
     * Product name exactly as it appeared in the source price list.
     */
    source_product_name: string;
    /**
     * Current product price from the source price list.
     */
    price_eur?: (string | null);
    /**
     * Original CSV column: cijena za jedinicu mjere (EUR) or CIJENA ZA JEDINICU MJERE.
     */
    unit_price_eur: string;
    /**
     * Whether price_eur comes from the special sale price column.
     */
    is_special_sale?: boolean;
    /**
     * Name of the imported source CSV file.
     */
    source_file_name?: (string | null);
    id: string;
    retailer: RetailerPublic;
    store: StorePublic;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PriceMover = {
    product: ProductPublic;
    retailer: RetailerPublic;
    current_date: string;
    previous_date: string;
    previous_price_eur: string;
    current_price_eur: string;
    absolute_change_eur: string;
    percent_change: string;
};

export type PriceMoversPublic = {
    current_date: (string | null);
    previous_date: (string | null);
    price_drops: Array<PriceMover>;
    price_increases: Array<PriceMover>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductPublic = {
    /**
     * Cross retailer product identifier when present. Original CSV column: barkod or BARKOD.
     */
    barcode?: (string | null);
    /**
     * Canonical or first seen product name. Original CSV column: naziv or NAZIV PROIZVODA.
     */
    name: string;
    /**
     * Alternative product name fetched from Open Food Facts, preferring Croatian names.
     */
    alternative_name?: (string | null);
    /**
     * Original CSV column: marka or MARKA PROIZVODA.
     */
    brand?: (string | null);
    /**
     * Raw net quantity from the CSV. Original CSV column: neto količina or NETO KOLIČINA.
     */
    net_quantity?: (string | null);
    /**
     * Original CSV column: jedinica mjere or JEDINICA MJERE.
     */
    unit_of_measure?: (string | null);
    /**
     * Original CSV column: kategorija proizvoda or KATEGORIJA PROIZVODA.
     */
    category?: (string | null);
    /**
     * Product image URL fetched from Open Food Facts.
     */
    image_url?: (string | null);
    id: string;
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type RetailerDailyRetailPriceHistoryPoint = {
    retailer: RetailerPublic;
    observed_date: string;
    average_price_eur: (string | null);
    min_price_eur: (string | null);
    max_price_eur: (string | null);
    has_special_sale: boolean;
};

export type RetailerPriceObservationSummary = {
    retailer: RetailerPublic;
    observed_date: string;
    average_price_eur: (string | null);
    min_price_eur: (string | null);
    max_price_eur: (string | null);
    average_unit_price_eur: string;
    min_unit_price_eur: string;
    max_unit_price_eur: string;
    store_count: number;
    observation_count: number;
    has_store_price_variance: boolean;
    has_special_sale: boolean;
};

export type RetailerPublic = {
    /**
     * Retailer name, for example Konzum or Interspar.
     */
    name: string;
    id: string;
};

export type StorePublic = {
    retailer_id: string;
    /**
     * Retailer scoped store code from the source file or retailer data.
     */
    store_code: string;
    /**
     * Store name, for example a branch or supermarket name.
     */
    name: string;
    /**
     * Store address when available.
     */
    address?: string;
    /**
     * Prefix to be used in finding corresponding file in list of stores
     */
    prefix?: string;
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DashboardReadPriceMoversData = {
    limit?: number;
};

export type DashboardReadPriceMoversResponse = (PriceMoversPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsReadProductsData = {
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsReadProductData = {
    productId: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsProductPriceObservationsData = {
    productId: string;
};

export type ProductsProductPriceObservationsResponse = (Array<NestedPriceObservation>);

export type ProductsProductDailyRetailPriceHistoryChartData = {
    productId: string;
};

export type ProductsProductDailyRetailPriceHistoryChartResponse = (Array<RetailerDailyRetailPriceHistoryPoint>);

export type ProductsGroupedProductPriceObservationsData = {
    productId: string;
};

export type ProductsGroupedProductPriceObservationsResponse = (Array<RetailerPriceObservationSummary>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);