// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_receipts_create_receipt = {
    retailer_id: string;
    store_id?: (string | null);
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NestedPriceObservation = {
    product_id: string;
    retailer_id: string;
    store_id: string;
    /**
     * Date of the price list or observation.
     */
    observed_date: string;
    /**
     * Retailer scoped product code. Original CSV column: šifra or ŠIFRA PROIZVODA.
     */
    retailer_product_code: string;
    /**
     * Product name exactly as it appeared in the source price list.
     */
    source_product_name: string;
    /**
     * Current product price from the source price list.
     */
    price_eur?: (string | null);
    /**
     * Original CSV column: cijena za jedinicu mjere (EUR) or CIJENA ZA JEDINICU MJERE.
     */
    unit_price_eur: string;
    /**
     * Whether price_eur comes from the special sale price column.
     */
    is_special_sale?: boolean;
    /**
     * Name of the imported source CSV file.
     */
    source_file_name?: (string | null);
    id: string;
    retailer: RetailerPublic;
    store: StorePublic;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PriceMover = {
    product: ProductPublic;
    retailer: RetailerPublic;
    current_date: string;
    previous_date: string;
    previous_price_eur: string;
    current_price_eur: string;
    absolute_change_eur: string;
    percent_change: string;
};

export type PriceMoversPublic = {
    current_date: (string | null);
    previous_date: (string | null);
    price_drops: Array<PriceMover>;
    price_increases: Array<PriceMover>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductListBase = {
    /**
     * User-facing product list name, for example Weekly groceries.
     */
    name: string;
    /**
     * Optional notes about what this product list is for.
     */
    description?: (string | null);
};

export type ProductListItemAlternativeCreate = {
    product_id: string;
    similarity_score?: (number | string | null);
};

export type ProductListItemAlternativeDetailPublic = {
    product_list_item_id: string;
    product_id: string;
    similarity_score?: (string | null);
    created_at?: string;
    id: string;
    product: ProductPublic;
};

export type ProductListItemAlternativesBulkCreate = {
    product_ids: Array<(string)>;
    similarity_scores?: Record<string, (number | string)>;
};

export type ProductListItemAlternativesBulkCreateResult = {
    data: Array<ProductListItemAlternativeDetailPublic>;
    created_count: number;
    skipped_count: number;
};

export type ProductListItemCreate = {
    product_id: string;
    quantity?: (number | string);
    note?: (string | null);
};

export type ProductListItemDetailPublic = {
    product_list_id: string;
    product_id: string;
    /**
     * How many units of the canonical product are planned for this list.
     */
    quantity?: string;
    /**
     * Optional note for this list item.
     */
    note?: (string | null);
    created_at?: string;
    updated_at?: string;
    id: string;
    product: ProductPublic;
    alternatives?: Array<ProductListItemAlternativeDetailPublic>;
};

export type ProductListItemUpdate = {
    quantity?: (number | string | null);
    note?: (string | null);
};

export type ProductListPublic = {
    /**
     * User-facing product list name, for example Weekly groceries.
     */
    name: string;
    /**
     * Optional notes about what this product list is for.
     */
    description?: (string | null);
    id: string;
    created_at?: string;
    updated_at?: string;
};

export type ProductListRetailerPriceHistoryPoint = {
    retailer: RetailerPublic;
    observed_date: string;
    total_price_eur: string;
    matched_item_count: number;
    total_item_count: number;
    has_missing_prices: boolean;
    has_special_sale: boolean;
};

export type ProductListsPublic = {
    data: Array<ProductListPublic>;
    count: number;
};

export type ProductListUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ProductPublic = {
    /**
     * Cross retailer product identifier when present. Original CSV column: barkod or BARKOD.
     */
    barcode?: (string | null);
    /**
     * Canonical or first seen product name. Original CSV column: naziv or NAZIV PROIZVODA.
     */
    name: string;
    /**
     * Original CSV column: marka or MARKA PROIZVODA.
     */
    brand?: (string | null);
    /**
     * Raw net quantity from the CSV. Original CSV column: neto količina or NETO KOLIČINA.
     */
    net_quantity?: (string | null);
    /**
     * Original CSV column: jedinica mjere or JEDINICA MJERE.
     */
    unit_of_measure?: (string | null);
    /**
     * Original CSV column: kategorija proizvoda or KATEGORIJA PROIZVODA.
     */
    category?: (string | null);
    /**
     * Product image URL fetched from Open Food Facts.
     */
    image_url?: (string | null);
    id: string;
    /**
     * Product price from one latest available observation.
     */
    latest_price_eur?: (string | null);
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

export type ReceiptItemReviewPublic = {
    receipt_id: string;
    product_id?: (string | null);
    price_observation_id?: (string | null);
    line_number: number;
    /**
     * Product name exactly as parsed from the receipt.
     */
    raw_name: string;
    /**
     * Normalized search form of raw_name.
     */
    normalized_raw_name: string;
    /**
     * Purchased quantity parsed from the receipt line.
     */
    quantity: string;
    /**
     * Unit parsed from the receipt line when present, for example kg.
     */
    unit_of_measure?: (string | null);
    /**
     * Unit price in EUR parsed from the receipt line.
     */
    unit_price_eur?: (string | null);
    /**
     * Final line total in EUR after any receipt-level line adjustments.
     */
    line_total_eur: string;
    /**
     * Whether the user intentionally ignored this receipt line.
     */
    is_skipped?: boolean;
    created_at?: string;
    updated_at?: string;
    id: string;
    product?: (ProductPublic | null);
};

export type ReceiptItemUpdate = {
    product_id?: (string | null);
    is_skipped?: (boolean | null);
};

export type ReceiptPublic = {
    retailer_id: string;
    store_id?: (string | null);
    user_id?: (string | null);
    /**
     * Datetime when the purchase was made, as parsed from the receipt.
     */
    purchase_datetime?: (string | null);
    /**
     * Final receipt total in EUR.
     */
    total_eur?: (string | null);
    /**
     * Storage key or path for the uploaded receipt file.
     */
    file_key: string;
    /**
     * User review lifecycle status for the receipt.
     */
    status?: ReceiptStatus;
    /**
     * Text extracted from the uploaded receipt file.
     */
    raw_text?: (string | null);
    created_at?: string;
    updated_at?: string;
    id: string;
};

export type ReceiptsPublic = {
    data: Array<ReceiptPublic>;
    count: number;
};

export type ReceiptStatus = 'draft' | 'completed';

export type ReceiptUpdate = {
    status?: (ReceiptStatus | null);
};

export type RetailerDailyRetailPriceHistoryPoint = {
    retailer: RetailerPublic;
    observed_date: string;
    average_price_eur: (string | null);
    min_price_eur: (string | null);
    max_price_eur: (string | null);
    has_special_sale: boolean;
};

export type RetailerPriceObservationSummary = {
    retailer: RetailerPublic;
    observed_date: string;
    average_price_eur: (string | null);
    min_price_eur: (string | null);
    max_price_eur: (string | null);
    average_unit_price_eur: string;
    min_unit_price_eur: string;
    max_unit_price_eur: string;
    store_count: number;
    observation_count: number;
    has_store_price_variance: boolean;
    has_special_sale: boolean;
};

export type RetailerPublic = {
    /**
     * Retailer name, for example Konzum or Interspar.
     */
    name: string;
    id: string;
};

export type SimilarProductPublic = {
    product: ProductPublic;
    retailers: Array<RetailerPublic>;
    latest_price_eur: (string | null);
    average_price_eur: (string | null);
    latest_observed_date: (string | null);
    score: string;
};

export type StorePublic = {
    retailer_id: string;
    /**
     * Retailer scoped store code from the source file or retailer data.
     */
    store_code: string;
    /**
     * Store name, for example a branch or supermarket name.
     */
    name: string;
    /**
     * Store address when available.
     */
    address?: string;
    /**
     * Prefix to be used in finding corresponding file in list of stores
     */
    prefix?: string;
    id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DashboardReadPriceMoversData = {
    limit?: number;
};

export type DashboardReadPriceMoversResponse = (PriceMoversPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductListsCreateProductListData = {
    requestBody: ProductListBase;
};

export type ProductListsCreateProductListResponse = (ProductListPublic);

export type ProductListsReadProductListsData = {
    limit?: number;
    skip?: number;
};

export type ProductListsReadProductListsResponse = (ProductListsPublic);

export type ProductListsCreateProductListFromReceiptData = {
    receiptId: string;
    requestBody: ProductListBase;
};

export type ProductListsCreateProductListFromReceiptResponse = (ProductListPublic);

export type ProductListsReadProductListData = {
    productListId: string;
};

export type ProductListsReadProductListResponse = (ProductListPublic);

export type ProductListsUpdateProductListData = {
    productListId: string;
    requestBody: ProductListUpdate;
};

export type ProductListsUpdateProductListResponse = (ProductListPublic);

export type ProductListsDeleteProductListData = {
    productListId: string;
};

export type ProductListsDeleteProductListResponse = (void);

export type ProductListsProductListRetailPriceHistoryChartData = {
    alternativeFallbackOrder?: 'cheapest' | 'similar';
    productListId: string;
};

export type ProductListsProductListRetailPriceHistoryChartResponse = (Array<ProductListRetailerPriceHistoryPoint>);

export type ProductListsReadProductListItemsData = {
    productListId: string;
};

export type ProductListsReadProductListItemsResponse = (Array<ProductListItemDetailPublic>);

export type ProductListsCreateProductListItemData = {
    productListId: string;
    requestBody: ProductListItemCreate;
};

export type ProductListsCreateProductListItemResponse = (ProductListItemDetailPublic);

export type ProductListsUpdateProductListItemData = {
    itemId: string;
    productListId: string;
    requestBody: ProductListItemUpdate;
};

export type ProductListsUpdateProductListItemResponse = (ProductListItemDetailPublic);

export type ProductListsDeleteProductListItemData = {
    itemId: string;
    productListId: string;
};

export type ProductListsDeleteProductListItemResponse = (void);

export type ProductListsReadProductListItemAlternativesData = {
    itemId: string;
    productListId: string;
};

export type ProductListsReadProductListItemAlternativesResponse = (Array<ProductListItemAlternativeDetailPublic>);

export type ProductListsCreateProductListItemAlternativeData = {
    itemId: string;
    productListId: string;
    requestBody: ProductListItemAlternativeCreate;
};

export type ProductListsCreateProductListItemAlternativeResponse = (ProductListItemAlternativeDetailPublic);

export type ProductListsBulkCreateProductListItemAlternativesData = {
    itemId: string;
    productListId: string;
    requestBody: ProductListItemAlternativesBulkCreate;
};

export type ProductListsBulkCreateProductListItemAlternativesResponse = (ProductListItemAlternativesBulkCreateResult);

export type ProductListsDeleteProductListItemAlternativeData = {
    alternativeId: string;
    itemId: string;
    productListId: string;
};

export type ProductListsDeleteProductListItemAlternativeResponse = (void);

export type ProductsReadProductsData = {
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsReadProductData = {
    productId: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsReadSimilarProductsData = {
    limit?: number;
    productId: string;
};

export type ProductsReadSimilarProductsResponse = (Array<SimilarProductPublic>);

export type ProductsProductPriceObservationsData = {
    productId: string;
};

export type ProductsProductPriceObservationsResponse = (Array<NestedPriceObservation>);

export type ProductsProductDailyRetailPriceHistoryChartData = {
    productId: string;
};

export type ProductsProductDailyRetailPriceHistoryChartResponse = (Array<RetailerDailyRetailPriceHistoryPoint>);

export type ProductsGroupedProductPriceObservationsData = {
    productId: string;
};

export type ProductsGroupedProductPriceObservationsResponse = (Array<RetailerPriceObservationSummary>);

export type ReceiptsCreateReceiptData = {
    formData: Body_receipts_create_receipt;
};

export type ReceiptsCreateReceiptResponse = (ReceiptPublic);

export type ReceiptsReadReceiptsData = {
    limit?: number;
    skip?: number;
};

export type ReceiptsReadReceiptsResponse = (ReceiptsPublic);

export type ReceiptsReadReceiptData = {
    receiptId: string;
};

export type ReceiptsReadReceiptResponse = (ReceiptPublic);

export type ReceiptsUpdateReceiptData = {
    receiptId: string;
    requestBody: ReceiptUpdate;
};

export type ReceiptsUpdateReceiptResponse = (ReceiptPublic);

export type ReceiptsDeleteReceiptData = {
    receiptId: string;
};

export type ReceiptsDeleteReceiptResponse = (void);

export type ReceiptsReadReceiptItemsData = {
    receiptId: string;
};

export type ReceiptsReadReceiptItemsResponse = (Array<ReceiptItemReviewPublic>);

export type ReceiptsUpdateReceiptItemData = {
    itemId: string;
    receiptId: string;
    requestBody: ReceiptItemUpdate;
};

export type ReceiptsUpdateReceiptItemResponse = (ReceiptItemReviewPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);