"""Remove useless index

Revision ID: 103bb4712995
Revises: 471076d1809d
Create Date: 2026-06-08 17:14:56.795388

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '103bb4712995'
down_revision = '471076d1809d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productalias_retailer_product_code'), table_name='productalias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_productalias_retailer_product_code'), 'productalias', ['retailer_product_code'], unique=False)
    # ### end Alembic commands ###
