"""Add price observation index

Revision ID: 471076d1809d
Revises: df709036f2de
Create Date: 2026-06-08 16:52:22.182697

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '471076d1809d'
down_revision = 'df709036f2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_priceobservation_retailer_code', 'priceobservation', ['retailer_id', 'retailer_product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_priceobservation_retailer_code', table_name='priceobservation')
    # ### end Alembic commands ###
