"""Add new store tables

Revision ID: a83e89cd46cb
Revises: 0001_base_schema
Create Date: 2026-04-28 03:20:37.302495

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a83e89cd46cb'
down_revision = '0001_base_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('net_quantity', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('unit_of_measure', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_barcode'), 'product', ['barcode'], unique=True)
    op.create_index(op.f('ix_product_brand'), 'product', ['brand'], unique=False)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('retailer',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_name'), 'retailer', ['name'], unique=True)
    op.create_table('store',
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('store_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'store_code', name='uq_store_retailer_code')
    )
    op.create_index(op.f('ix_store_retailer_id'), 'store', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_store_store_code'), 'store', ['store_code'], unique=False)
    op.create_table('priceobservation',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('observed_date', sa.Date(), nullable=False),
    sa.Column('retailer_product_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('source_product_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('retail_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_sale_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source_file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'store_id', 'observed_date', 'retailer_product_code', name='uq_price_observation_retailer_store_date_code')
    )
    op.create_index(op.f('ix_priceobservation_observed_date'), 'priceobservation', ['observed_date'], unique=False)
    op.create_index(op.f('ix_priceobservation_product_id'), 'priceobservation', ['product_id'], unique=False)
    op.create_index(op.f('ix_priceobservation_retailer_id'), 'priceobservation', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_priceobservation_retailer_product_code'), 'priceobservation', ['retailer_product_code'], unique=False)
    op.create_index(op.f('ix_priceobservation_store_id'), 'priceobservation', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priceobservation_store_id'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_retailer_product_code'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_retailer_id'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_product_id'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_observed_date'), table_name='priceobservation')
    op.drop_table('priceobservation')
    op.drop_index(op.f('ix_store_store_code'), table_name='store')
    op.drop_index(op.f('ix_store_retailer_id'), table_name='store')
    op.drop_table('store')
    op.drop_index(op.f('ix_retailer_name'), table_name='retailer')
    op.drop_table('retailer')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_index(op.f('ix_product_brand'), table_name='product')
    op.drop_index(op.f('ix_product_barcode'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
