"""empty message

Revision ID: df709036f2de
Revises: 0015_price_chart_lookup_idx
Create Date: 2026-06-08 16:45:13.294898

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'df709036f2de'
down_revision = '0015_price_chart_lookup_idx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priceobservation_observed_date_product_retailer_store'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_product_price'), table_name='priceobservation')
    op.drop_index(op.f('ix_priceobservation_product_retailer_date_price_not_null'), table_name='priceobservation', postgresql_where='(price_eur IS NOT NULL)', postgresql_include=['price_eur', 'is_special_sale'])
    op.drop_index(op.f('ix_product_lower_brand_trgm'), table_name='product', postgresql_ops={'lower(brand::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_product_lower_category_trgm'), table_name='product', postgresql_ops={'lower(category::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_product_lower_name_trgm'), table_name='product', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_productalias_lower_alias_name_trgm'), table_name='productalias', postgresql_ops={'lower(alias_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_productalias_lower_normalized_alias_name_trgm'), table_name='productalias', postgresql_ops={'lower(normalized_alias_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_productalias_source'), table_name='productalias')
    op.drop_constraint(op.f('productlistitemalternative_product_list_item_id_fkey'), 'productlistitemalternative', type_='foreignkey')
    op.create_foreign_key(None, 'productlistitemalternative', 'productlistitem', ['product_list_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productlistitemalternative', type_='foreignkey')
    op.create_foreign_key(op.f('productlistitemalternative_product_list_item_id_fkey'), 'productlistitemalternative', 'productlistitem', ['product_list_item_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_productalias_source'), 'productalias', ['source'], unique=False)
    op.create_index(op.f('ix_productalias_lower_normalized_alias_name_trgm'), 'productalias', [sa.literal_column('lower(normalized_alias_name::text)')], unique=False, postgresql_ops={'lower(normalized_alias_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_productalias_lower_alias_name_trgm'), 'productalias', [sa.literal_column('lower(alias_name::text)')], unique=False, postgresql_ops={'lower(alias_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_product_lower_name_trgm'), 'product', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_product_lower_category_trgm'), 'product', [sa.literal_column('lower(category::text)')], unique=False, postgresql_ops={'lower(category::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_product_lower_brand_trgm'), 'product', [sa.literal_column('lower(brand::text)')], unique=False, postgresql_ops={'lower(brand::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_priceobservation_product_retailer_date_price_not_null'), 'priceobservation', ['product_id', 'retailer_id', 'observed_date'], unique=False, postgresql_where='(price_eur IS NOT NULL)', postgresql_include=['price_eur', 'is_special_sale'])
    op.create_index(op.f('ix_priceobservation_product_price'), 'priceobservation', ['product_id', 'price_eur'], unique=False)
    op.create_index(op.f('ix_priceobservation_observed_date_product_retailer_store'), 'priceobservation', ['observed_date', 'product_id', 'retailer_id', 'store_id'], unique=False)
    # ### end Alembic commands ###
