"""add observation_count to observation daily

Revision ID: e19ee61dac5c
Revises: 1ee8a2394d07
Create Date: 2026-06-08 20:30:39.433990

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e19ee61dac5c'
down_revision = '1ee8a2394d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priceobservationdaily', sa.Column('observation_count', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priceobservationdaily', 'observation_count')
    # ### end Alembic commands ###
