"""Update store table

Revision ID: e1c71ea8a68c
Revises: a83e89cd46cb
Create Date: 2026-04-28 11:46:29.002312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1c71ea8a68c'
down_revision = 'a83e89cd46cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.alter_column('store', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('store', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('store', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('store', 'prefix')
    # ### end Alembic commands ###
