"""add unit_price to observation daily

Revision ID: f044033a6749
Revises: e19ee61dac5c
Create Date: 2026-06-08 20:48:55.886878

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f044033a6749'
down_revision = 'e19ee61dac5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priceobservationdaily', sa.Column('unit_price_eur_min', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('priceobservationdaily', sa.Column('unit_price_eur_max', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('priceobservationdaily', sa.Column('unit_price_eur_avg', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priceobservationdaily', 'unit_price_eur_avg')
    op.drop_column('priceobservationdaily', 'unit_price_eur_max')
    op.drop_column('priceobservationdaily', 'unit_price_eur_min')
    # ### end Alembic commands ###
