/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReceiptsRouteImport } from './routes/_layout/receipts'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutProductListsRouteImport } from './routes/_layout/product-lists'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutReceiptsIndexRouteImport } from './routes/_layout/receipts.index'
import { Route as LayoutProductsIndexRouteImport } from './routes/_layout/products.index'
import { Route as LayoutProductListsIndexRouteImport } from './routes/_layout/product-lists.index'
import { Route as LayoutReceiptsReceiptIdRouteImport } from './routes/_layout/receipts.$receiptId'
import { Route as LayoutProductsProductIdRouteImport } from './routes/_layout/products.$productId'
import { Route as LayoutProductListsProductListIdRouteImport } from './routes/_layout/product-lists.$productListId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiptsRoute = LayoutReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductListsRoute = LayoutProductListsRouteImport.update({
  id: '/product-lists',
  path: '/product-lists',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReceiptsIndexRoute = LayoutReceiptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutReceiptsRoute,
} as any)
const LayoutProductsIndexRoute = LayoutProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProductsRoute,
} as any)
const LayoutProductListsIndexRoute = LayoutProductListsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProductListsRoute,
} as any)
const LayoutReceiptsReceiptIdRoute = LayoutReceiptsReceiptIdRouteImport.update({
  id: '/$receiptId',
  path: '/$receiptId',
  getParentRoute: () => LayoutReceiptsRoute,
} as any)
const LayoutProductsProductIdRoute = LayoutProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => LayoutProductsRoute,
} as any)
const LayoutProductListsProductListIdRoute =
  LayoutProductListsProductListIdRouteImport.update({
    id: '/$productListId',
    path: '/$productListId',
    getParentRoute: () => LayoutProductListsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/product-lists': typeof LayoutProductListsRouteWithChildren
  '/products': typeof LayoutProductsRouteWithChildren
  '/receipts': typeof LayoutReceiptsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/product-lists/$productListId': typeof LayoutProductListsProductListIdRoute
  '/products/$productId': typeof LayoutProductsProductIdRoute
  '/receipts/$receiptId': typeof LayoutReceiptsReceiptIdRoute
  '/product-lists/': typeof LayoutProductListsIndexRoute
  '/products/': typeof LayoutProductsIndexRoute
  '/receipts/': typeof LayoutReceiptsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/product-lists/$productListId': typeof LayoutProductListsProductListIdRoute
  '/products/$productId': typeof LayoutProductsProductIdRoute
  '/receipts/$receiptId': typeof LayoutReceiptsReceiptIdRoute
  '/product-lists': typeof LayoutProductListsIndexRoute
  '/products': typeof LayoutProductsIndexRoute
  '/receipts': typeof LayoutReceiptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/product-lists': typeof LayoutProductListsRouteWithChildren
  '/_layout/products': typeof LayoutProductsRouteWithChildren
  '/_layout/receipts': typeof LayoutReceiptsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/product-lists/$productListId': typeof LayoutProductListsProductListIdRoute
  '/_layout/products/$productId': typeof LayoutProductsProductIdRoute
  '/_layout/receipts/$receiptId': typeof LayoutReceiptsReceiptIdRoute
  '/_layout/product-lists/': typeof LayoutProductListsIndexRoute
  '/_layout/products/': typeof LayoutProductsIndexRoute
  '/_layout/receipts/': typeof LayoutReceiptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/product-lists'
    | '/products'
    | '/receipts'
    | '/settings'
    | '/product-lists/$productListId'
    | '/products/$productId'
    | '/receipts/$receiptId'
    | '/product-lists/'
    | '/products/'
    | '/receipts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/product-lists/$productListId'
    | '/products/$productId'
    | '/receipts/$receiptId'
    | '/product-lists'
    | '/products'
    | '/receipts'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/product-lists'
    | '/_layout/products'
    | '/_layout/receipts'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/product-lists/$productListId'
    | '/_layout/products/$productId'
    | '/_layout/receipts/$receiptId'
    | '/_layout/product-lists/'
    | '/_layout/products/'
    | '/_layout/receipts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receipts': {
      id: '/_layout/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof LayoutReceiptsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product-lists': {
      id: '/_layout/product-lists'
      path: '/product-lists'
      fullPath: '/product-lists'
      preLoaderRoute: typeof LayoutProductListsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/receipts/': {
      id: '/_layout/receipts/'
      path: '/'
      fullPath: '/receipts/'
      preLoaderRoute: typeof LayoutReceiptsIndexRouteImport
      parentRoute: typeof LayoutReceiptsRoute
    }
    '/_layout/products/': {
      id: '/_layout/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof LayoutProductsIndexRouteImport
      parentRoute: typeof LayoutProductsRoute
    }
    '/_layout/product-lists/': {
      id: '/_layout/product-lists/'
      path: '/'
      fullPath: '/product-lists/'
      preLoaderRoute: typeof LayoutProductListsIndexRouteImport
      parentRoute: typeof LayoutProductListsRoute
    }
    '/_layout/receipts/$receiptId': {
      id: '/_layout/receipts/$receiptId'
      path: '/$receiptId'
      fullPath: '/receipts/$receiptId'
      preLoaderRoute: typeof LayoutReceiptsReceiptIdRouteImport
      parentRoute: typeof LayoutReceiptsRoute
    }
    '/_layout/products/$productId': {
      id: '/_layout/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof LayoutProductsProductIdRouteImport
      parentRoute: typeof LayoutProductsRoute
    }
    '/_layout/product-lists/$productListId': {
      id: '/_layout/product-lists/$productListId'
      path: '/$productListId'
      fullPath: '/product-lists/$productListId'
      preLoaderRoute: typeof LayoutProductListsProductListIdRouteImport
      parentRoute: typeof LayoutProductListsRoute
    }
  }
}

interface LayoutProductListsRouteChildren {
  LayoutProductListsProductListIdRoute: typeof LayoutProductListsProductListIdRoute
  LayoutProductListsIndexRoute: typeof LayoutProductListsIndexRoute
}

const LayoutProductListsRouteChildren: LayoutProductListsRouteChildren = {
  LayoutProductListsProductListIdRoute: LayoutProductListsProductListIdRoute,
  LayoutProductListsIndexRoute: LayoutProductListsIndexRoute,
}

const LayoutProductListsRouteWithChildren =
  LayoutProductListsRoute._addFileChildren(LayoutProductListsRouteChildren)

interface LayoutProductsRouteChildren {
  LayoutProductsProductIdRoute: typeof LayoutProductsProductIdRoute
  LayoutProductsIndexRoute: typeof LayoutProductsIndexRoute
}

const LayoutProductsRouteChildren: LayoutProductsRouteChildren = {
  LayoutProductsProductIdRoute: LayoutProductsProductIdRoute,
  LayoutProductsIndexRoute: LayoutProductsIndexRoute,
}

const LayoutProductsRouteWithChildren = LayoutProductsRoute._addFileChildren(
  LayoutProductsRouteChildren,
)

interface LayoutReceiptsRouteChildren {
  LayoutReceiptsReceiptIdRoute: typeof LayoutReceiptsReceiptIdRoute
  LayoutReceiptsIndexRoute: typeof LayoutReceiptsIndexRoute
}

const LayoutReceiptsRouteChildren: LayoutReceiptsRouteChildren = {
  LayoutReceiptsReceiptIdRoute: LayoutReceiptsReceiptIdRoute,
  LayoutReceiptsIndexRoute: LayoutReceiptsIndexRoute,
}

const LayoutReceiptsRouteWithChildren = LayoutReceiptsRoute._addFileChildren(
  LayoutReceiptsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutProductListsRoute: typeof LayoutProductListsRouteWithChildren
  LayoutProductsRoute: typeof LayoutProductsRouteWithChildren
  LayoutReceiptsRoute: typeof LayoutReceiptsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutProductListsRoute: LayoutProductListsRouteWithChildren,
  LayoutProductsRoute: LayoutProductsRouteWithChildren,
  LayoutReceiptsRoute: LayoutReceiptsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
